#!/usr/bin/python

import sys
from subprocess import call

totalArguments = len(sys.argv)
argumentsList = str(sys.argv)

def printHelp():
	print ("Usage: mysqlc-create-database [MYSQL CONTAINER NAME] [DATABASE NAME]")
	print ("")
	print ("Example:")
	print ("mysqlc-create-database mysql blog")
	return

def runContainer(containerName, databaseName):
	call("docker run -it --link="+containerName+":mysql --rm mysql sh -c 'exec mysqladmin -h$MYSQL_PORT_3306_TCP_ADDR -P$MYSQL_PORT_3306_TCP_PORT -uroot -p create "+ databaseName +" '", shell=True)
	return

def main():
	if totalArguments == 1:
		printHelp()

	if "--help" in argumentsList:
		printHelp()

	if "-h" in argumentsList:
		printHelp()

	if totalArguments > 1:
		if "--help" not in argumentsList and "-h" not in argumentsList:
			runContainer(sys.argv[1], sys.argv[2])
	return

main()